/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home.my_recipes;

import database.databaseConnect;
import home.common_panel.home_panel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import time.to.cook.mainPage_frame;

/**
 *
 * @author Supun
 */
public class myRecipesAdd_dForm extends javax.swing.JDialog {

    Connection con = null;
    PreparedStatement pst = null;
    
    
    /**
     * Creates new form myRecipesAdd_dForm
     * @param parent
     * @param modal
     */
    public myRecipesAdd_dForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents(); 
        
        
        //  connect to Database
        con = databaseConnect.connect();
        
        //hide password input boxers
        firstPassword_textField.setVisible(false);
        secondPassword_textField.setVisible(false);
        EnterPassword_label.setVisible(false);
        cofirmPassword_label.setVisible(false);
        
    }

    myRecipesAdd_dForm() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        methords_table = new javax.swing.JTable();
        submit_Button = new javax.swing.JButton();
        cancel_Button = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        shortDis_textArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        password_CheckBox = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        foodName_textBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AmountOfPortion_spinner = new javax.swing.JSpinner();
        EnterPassword_label = new javax.swing.JLabel();
        cofirmPassword_label = new javax.swing.JLabel();
        firstPassword_textField = new javax.swing.JTextField();
        secondPassword_textField = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        ingredianAmount_table1 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        extraNote_tArea = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        item_textBox = new javax.swing.JTextField();
        measurment_comboBox = new javax.swing.JComboBox();
        ingredientsAdd_button = new javax.swing.JButton();
        ingredientsRemove_button = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        amount_spinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        methords_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "No", "Methord", "Time (minutes)", "Tips"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(methords_table);
        if (methords_table.getColumnModel().getColumnCount() > 0) {
            methords_table.getColumnModel().getColumn(0).setPreferredWidth(45);
            methords_table.getColumnModel().getColumn(0).setMaxWidth(50);
            methords_table.getColumnModel().getColumn(2).setPreferredWidth(100);
            methords_table.getColumnModel().getColumn(2).setMaxWidth(150);
        }

        submit_Button.setText("Submit");
        submit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_ButtonActionPerformed(evt);
            }
        });

        cancel_Button.setText("Cancel");
        cancel_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_ButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Add methords details");

        jLabel4.setText("Add ingredient details");

        shortDis_textArea.setColumns(20);
        shortDis_textArea.setRows(5);
        jScrollPane1.setViewportView(shortDis_textArea);

        jLabel3.setText("Short description");

        jLabel2.setText("Image");

        password_CheckBox.setText("This is Secret recipe and Insert password to menu.");
        password_CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_CheckBoxActionPerformed(evt);
            }
        });

        jButton1.setText("Source file");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Food Name");

        jLabel6.setText("Amount of Portion");

        EnterPassword_label.setText("Enter password");

        cofirmPassword_label.setText("Confirm password");

        firstPassword_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstPassword_textFieldActionPerformed(evt);
            }
        });

        secondPassword_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondPassword_textFieldActionPerformed(evt);
            }
        });

        ingredianAmount_table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Amount", "Measurments"
            }
        ));
        jScrollPane4.setViewportView(ingredianAmount_table1);
        if (ingredianAmount_table1.getColumnModel().getColumnCount() > 0) {
            ingredianAmount_table1.getColumnModel().getColumn(1).setPreferredWidth(110);
            ingredianAmount_table1.getColumnModel().getColumn(1).setMaxWidth(150);
            ingredianAmount_table1.getColumnModel().getColumn(2).setPreferredWidth(110);
            ingredianAmount_table1.getColumnModel().getColumn(2).setMaxWidth(150);
        }

        extraNote_tArea.setColumns(20);
        extraNote_tArea.setRows(5);
        jScrollPane2.setViewportView(extraNote_tArea);

        jScrollPane5.setViewportView(jScrollPane2);

        jLabel7.setText("Extra Notes : ");

        item_textBox.setText("Enter item name");
        item_textBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item_textBoxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                item_textBoxMouseEntered(evt);
            }
        });
        item_textBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_textBoxActionPerformed(evt);
            }
        });

        measurment_comboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Fluid --", "MiliFram (ml)", "Flude ounce (ft)", "Pint (pt)", "Quart (qt)", "Cups", "Gallom (gal)", "Pound ", "Ounce (oz)", "inch (in)", "cubic centimeter (cc)", " ", "--Weight--", "gram (g)" }));

        ingredientsAdd_button.setText("Add");
        ingredientsAdd_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredientsAdd_buttonActionPerformed(evt);
            }
        });

        ingredientsRemove_button.setText("Remove");
        ingredientsRemove_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredientsRemove_buttonActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane6.setViewportView(jTextArea1);

        jButton4.setText("Add");

        jButton5.setText("Remove");

        jButton6.setText("Up");

        jButton7.setText("Down");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(41, 41, 41)
                            .addComponent(foodName_textBox, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(8, 8, 8)
                            .addComponent(AmountOfPortion_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(password_CheckBox)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addComponent(EnterPassword_label)
                                        .addGap(27, 27, 27))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cofirmPassword_label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(firstPassword_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(secondPassword_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(81, 81, 81)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ingredientsRemove_button))
                                .addComponent(jScrollPane3)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane6)
                                        .addComponent(jTextField3))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField4)
                                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(submit_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancel_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(item_textBox)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(amount_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(measurment_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ingredientsAdd_button, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(foodName_textBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(AmountOfPortion_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(password_CheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnterPassword_label)
                    .addComponent(firstPassword_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secondPassword_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cofirmPassword_label)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(submit_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancel_Button)
                        .addGap(304, 304, 304))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(item_textBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(measurment_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ingredientsAdd_button)
                            .addComponent(amount_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ingredientsRemove_button, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );

        setSize(new java.awt.Dimension(1180, 664));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancel_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_ButtonActionPerformed
        //mainPage mPage= new mainPage();
        //mPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancel_ButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void firstPassword_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstPassword_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstPassword_textFieldActionPerformed

    private void secondPassword_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondPassword_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondPassword_textFieldActionPerformed

    private void submit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_ButtonActionPerformed
        String recipeName = foodName_textBox.getText();
        String shortDis = shortDis_textArea.getText();
        int numberOfPortion =  AmountOfPortion_spinner.getComponentCount();
        String note = extraNote_tArea.getText();
        
        try {
            String q = "INSERT INTO myrecipes (rName,rShortDiscription,rPortionAmount,rFullDiscription) values ('"+recipeName+"','"+shortDis+"','"+numberOfPortion+"','"+note+"')";
            pst = con.prepareStatement(q);
            pst.execute();
        } catch (Exception e) {
            System.out.println("Error : "+e);
        }
        
        // refresh myRecipesList_table
        home_panel objHome_panel = new home_panel();
        
        objHome_panel.myRecipeList_tableload();
        objHome_panel.myRecipeList_tableload();
        
        this.dispose();
    }//GEN-LAST:event_submit_ButtonActionPerformed

    private void password_CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_CheckBoxActionPerformed
        boolean x = password_CheckBox.isSelected();
        if(x==true){
        firstPassword_textField.setVisible(true);
        secondPassword_textField.setVisible(true);
        EnterPassword_label.setVisible(true);
        cofirmPassword_label.setVisible(true);
        
        }
        if(x==false){
            firstPassword_textField.setVisible(false);
            secondPassword_textField.setVisible(false);
            EnterPassword_label.setVisible(false);
            cofirmPassword_label.setVisible(false);
        
        }
    }//GEN-LAST:event_password_CheckBoxActionPerformed

    private void item_textBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_textBoxActionPerformed
        String tBoxText = item_textBox.getText();
        if (tBoxText=="Enter item name"){
            item_textBox.setText("");
        }
    }//GEN-LAST:event_item_textBoxActionPerformed

    private void ingredientsAdd_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredientsAdd_buttonActionPerformed
        String itemText=item_textBox.getText();
        String amountText=amount_spinner.getValue().toString();
        String measurementText=Arrays.toString(measurment_comboBox.getSelectedObjects());
        
        JOptionPane.showMessageDialog(null,"itemText : "+itemText+"\namountText : "+amountText+"\nmeasurementText :"+measurementText);
        
        DefaultTableModel model=(DefaultTableModel) ingredianAmount_table1.getModel();
        model.addRow(new Object[]{itemText,amountText,measurementText});
    }//GEN-LAST:event_ingredientsAdd_buttonActionPerformed

    private void ingredientsRemove_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredientsRemove_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingredientsRemove_buttonActionPerformed

    private void item_textBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item_textBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_item_textBoxMouseClicked

    private void item_textBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item_textBoxMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_item_textBoxMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myRecipesAdd_dForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myRecipesAdd_dForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myRecipesAdd_dForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myRecipesAdd_dForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                myRecipesAdd_dForm dialog = new myRecipesAdd_dForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner AmountOfPortion_spinner;
    private javax.swing.JLabel EnterPassword_label;
    private javax.swing.JSpinner amount_spinner;
    private javax.swing.JButton cancel_Button;
    private javax.swing.JLabel cofirmPassword_label;
    private javax.swing.JTextArea extraNote_tArea;
    private javax.swing.JTextField firstPassword_textField;
    private javax.swing.JTextField foodName_textBox;
    private javax.swing.JTable ingredianAmount_table1;
    private javax.swing.JButton ingredientsAdd_button;
    private javax.swing.JButton ingredientsRemove_button;
    private javax.swing.JTextField item_textBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JComboBox measurment_comboBox;
    private javax.swing.JTable methords_table;
    private javax.swing.JCheckBox password_CheckBox;
    private javax.swing.JTextField secondPassword_textField;
    private javax.swing.JTextArea shortDis_textArea;
    private javax.swing.JButton submit_Button;
    // End of variables declaration//GEN-END:variables
}
