/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package time.to.cook;

import home.common_panel.home_panel;
import feature.time_counter.timeCounter_panel;
import feature.recipe_arranger.recipeArranger_panel;
import feature.emergency_unit.emergencyUnit_panel;
import feature.food_for_health.foodForHealth_panel;
import feature.reference.reference_panel;

/**
 *
 * @author Supun
 */
public class mainPage_frame extends javax.swing.JFrame {

    /**
     * Creates new form mainPage_frame
     */
    public mainPage_frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPage_jScrollPane = new javax.swing.JScrollPane();
        reference_button = new javax.swing.JButton();
        emergencyUnit_button = new javax.swing.JButton();
        foodForHealth_button = new javax.swing.JButton();
        timeCounter_button = new javax.swing.JButton();
        recipeArranger_button = new javax.swing.JButton();
        home_button = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Time To Cook (Food Recipes Arranging System) v.Beta");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        reference_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/refere.png"))); // NOI18N
        reference_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reference_buttonActionPerformed(evt);
            }
        });

        emergencyUnit_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/Emergency unit.png"))); // NOI18N
        emergencyUnit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergencyUnit_buttonActionPerformed(evt);
            }
        });

        foodForHealth_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/food for health.png"))); // NOI18N
        foodForHealth_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodForHealth_buttonActionPerformed(evt);
            }
        });

        timeCounter_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/Time.png"))); // NOI18N
        timeCounter_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeCounter_buttonActionPerformed(evt);
            }
        });

        recipeArranger_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/recipe arranger.png"))); // NOI18N
        recipeArranger_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recipeArranger_buttonActionPerformed(evt);
            }
        });

        home_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icons/home.png"))); // NOI18N
        home_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_buttonActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Exit");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem2.setText("jMenuItem2");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("jMenuItem3");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPage_jScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(home_button, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recipeArranger_button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeCounter_button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(foodForHealth_button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emergencyUnit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reference_button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 56, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reference_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(foodForHealth_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(home_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(recipeArranger_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(timeCounter_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emergencyUnit_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainPage_jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        setSize(new java.awt.Dimension(1317, 722));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        setDefaultCloseOperation(mainPage_frame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void recipeArranger_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recipeArranger_buttonActionPerformed
        recipeArranger_panel home = new recipeArranger_panel();
        mainPage_jScrollPane.setViewportView(home);
    }//GEN-LAST:event_recipeArranger_buttonActionPerformed

    private void foodForHealth_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodForHealth_buttonActionPerformed
        foodForHealth_panel home = new foodForHealth_panel();
        mainPage_jScrollPane.setViewportView(home);
    }//GEN-LAST:event_foodForHealth_buttonActionPerformed

    private void home_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_buttonActionPerformed
        home_panel home = new home_panel();
        mainPage_jScrollPane.setViewportView(home);
    }//GEN-LAST:event_home_buttonActionPerformed

    private void timeCounter_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeCounter_buttonActionPerformed
        timeCounter_panel home = new timeCounter_panel();
        mainPage_jScrollPane.setViewportView(home);
    }//GEN-LAST:event_timeCounter_buttonActionPerformed

    private void emergencyUnit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergencyUnit_buttonActionPerformed
        emergencyUnit_panel home = new emergencyUnit_panel();
        mainPage_jScrollPane.setViewportView(home);
    }//GEN-LAST:event_emergencyUnit_buttonActionPerformed

    private void reference_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reference_buttonActionPerformed
        reference_panel home = new reference_panel();
        mainPage_jScrollPane.setViewportView(home);
    }//GEN-LAST:event_reference_buttonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        home_panel home = new home_panel();
        mainPage_jScrollPane.setViewportView(home);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainPage_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainPage_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainPage_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainPage_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainPage_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton emergencyUnit_button;
    private javax.swing.JButton foodForHealth_button;
    private javax.swing.JButton home_button;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane mainPage_jScrollPane;
    private javax.swing.JButton recipeArranger_button;
    private javax.swing.JButton reference_button;
    private javax.swing.JButton timeCounter_button;
    // End of variables declaration//GEN-END:variables
}
